# Generated by Django 4.2 on 2024-03-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_media_remove_video_product_delete_image_delete_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='video',
            new_name='media',
        ),
    ]
